#!/bin/bash
#
# analyze_with_gemini.sh - Analyze trending stocks report with Gemini CLI
#
# Usage: ./analyze_with_gemini.sh [report_file]
#
# Requires: gemini CLI installed and configured
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPORT_FILE="${1:-$SCRIPT_DIR/output/trending_report.json}"
DATE_STR=$(date +%Y-%m-%d)
OUTPUT_FILE="$SCRIPT_DIR/output/analysis_${DATE_STR}.md"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=============================================${NC}"
echo -e "${BLUE}       GEMINI AI STOCK ANALYSIS              ${NC}"
echo -e "${BLUE}=============================================${NC}"
echo ""

# Check if report file exists
if [[ ! -f "$REPORT_FILE" ]]; then
    echo -e "${RED}Error: Report file not found: $REPORT_FILE${NC}"
    echo "Run the trending stocks scanner first: python main.py"
    exit 1
fi

# Find gemini CLI
GEMINI_CMD=""
if [[ -x "/opt/homebrew/bin/gemini" ]]; then
    GEMINI_CMD="/opt/homebrew/bin/gemini"
elif [[ -x "/usr/local/bin/gemini" ]]; then
    GEMINI_CMD="/usr/local/bin/gemini"
elif command -v gemini &> /dev/null; then
    GEMINI_CMD="gemini"
fi

if [[ -z "$GEMINI_CMD" ]]; then
    echo -e "${YELLOW}Warning: gemini CLI not found.${NC}"
    echo "Install Gemini CLI or set up an alias."
    echo ""
    echo "Alternative: Copy the report and paste into Gemini web interface:"
    echo "  cat $REPORT_FILE"
    exit 1
fi

echo -e "${GREEN}Reading report from: $REPORT_FILE${NC}"
echo ""

# Build the prompt for comprehensive report
read -r -d '' PROMPT << 'EOF' || true
You are an expert quantitative trading analyst writing a comprehensive morning market report. Analyze this multi-source trending stocks data and produce a detailed professional report.

Write a FULL ANALYSIS REPORT with the following sections:

---

# DAILY MARKET INTELLIGENCE REPORT

## Executive Summary
A 2-3 paragraph overview of today's key findings. What is the market telling us? What are the dominant themes? What should traders focus on today?

## Market Regime & Sector Analysis
- Analyze the sector performance data
- Identify which sectors are leading/lagging
- Discuss sector rotation signals
- Note any divergences between sectors

## High Conviction Trade Ideas (Top 5)
For EACH idea provide:
| Ticker | Direction | Thesis | Entry Zone | Stop Loss | Target | Risk/Reward |
Include:
- Why this setup is compelling (momentum + sentiment + technicals)
- Key catalyst or driver
- What could go wrong
- Position sizing suggestion (small/medium/large)

## Technical Signals Analysis
### Momentum Leaders
- Analyze the top momentum stocks
- What do they have in common?
- Are they extended or just starting?

### Breakout Candidates (New Highs)
- Stocks making new highs with analysis
- Which are extended vs. buyable

### Mean Reversion Opportunities
- Analyze oversold stocks for bounce candidates
- Analyze overbought stocks for potential shorts/profit-taking

### Volume Anomalies
- Unusual volume stocks and what it might signal
- Accumulation vs distribution patterns

## Social Sentiment Analysis
### Reddit Sentiment
- What is retail focused on?
- Any concerning crowding in certain names?
- Sentiment divergences from price action

### News Flow
- Key news themes
- Stocks with catalyst-driven moves

## Risk Factors & Red Flags
- Stocks to AVOID and why
- Overbought/overcrowded names
- Potential bull/bear traps
- Macro risks to monitor today

## Watchlist Summary Table
| Priority | Ticker | Setup Type | Key Level | Action Trigger |
|----------|--------|------------|-----------|----------------|
(Include 10 tickers ranked by conviction)

## Trading Plan for Today
- Pre-market focus areas
- Key levels to watch on indices
- Optimal entry timing windows
- Risk management reminders

---

Be specific with numbers, levels, and actionable insights. Write for an experienced trader who wants depth, not surface-level commentary. Use the data provided to support every claim.

TRENDING STOCKS DATA:
EOF

# Append the JSON data
FULL_PROMPT="$PROMPT

$(cat "$REPORT_FILE")"

echo -e "${YELLOW}Calling Gemini (gemini-3-pro-preview) for analysis...${NC}"
echo ""

# Call Gemini CLI with latest pro model and capture output
ANALYSIS=$("$GEMINI_CMD" --model gemini-3-pro-preview "$FULL_PROMPT" 2>/dev/null)
EXIT_CODE=$?

if [[ $EXIT_CODE -eq 0 && -n "$ANALYSIS" ]]; then
    # Display to terminal
    echo "$ANALYSIS"

    # Save to file with header
    {
        echo "# Daily Market Intelligence Report - $DATE_STR"
        echo ""
        echo "_Generated by Gemini 3 Pro Preview at $(date +%H:%M)_"
        echo ""
        echo "---"
        echo ""
        echo "$ANALYSIS"
    } > "$OUTPUT_FILE"

    echo ""
    echo -e "${GREEN}=============================================${NC}"
    echo -e "${GREEN}Analysis complete.${NC}"
    echo -e "${GREEN}Saved to: $OUTPUT_FILE${NC}"
    echo -e "${GREEN}=============================================${NC}"
else
    echo ""
    echo -e "${YELLOW}Warning: Gemini analysis failed (exit code: $EXIT_CODE)${NC}"
    echo ""
    echo "Troubleshooting:"
    echo "  1. Check if gemini CLI is properly configured"
    echo "  2. Check your API key / authentication"
    echo "  3. Try running: $GEMINI_CMD --model gemini-3-pro-preview 'test'"
    echo ""
    echo "Manual option: Copy the JSON below and paste into Gemini web:"
    echo "----------------------------------------"
    head -50 "$REPORT_FILE"
    echo "..."
    echo "----------------------------------------"
    exit 1
fi
