#!/bin/bash
#
# analyze_with_gemini.sh - Analyze trending stocks report with Gemini CLI
#
# Usage: ./analyze_with_gemini.sh [report_file]
#
# Requires: gemini CLI installed and configured
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPORT_FILE="${1:-$SCRIPT_DIR/output/trending_report.json}"
DATE_STR=$(date +%Y-%m-%d)
OUTPUT_FILE="$SCRIPT_DIR/output/analysis_${DATE_STR}.md"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=============================================${NC}"
echo -e "${BLUE}       GEMINI AI STOCK ANALYSIS              ${NC}"
echo -e "${BLUE}=============================================${NC}"
echo ""

# Check if report file exists
if [[ ! -f "$REPORT_FILE" ]]; then
    echo -e "${RED}Error: Report file not found: $REPORT_FILE${NC}"
    echo "Run the trending stocks scanner first: python main.py"
    exit 1
fi

# Find gemini CLI
GEMINI_CMD=""
if [[ -x "/opt/homebrew/bin/gemini" ]]; then
    GEMINI_CMD="/opt/homebrew/bin/gemini"
elif [[ -x "/usr/local/bin/gemini" ]]; then
    GEMINI_CMD="/usr/local/bin/gemini"
elif command -v gemini &> /dev/null; then
    GEMINI_CMD="gemini"
fi

if [[ -z "$GEMINI_CMD" ]]; then
    echo -e "${YELLOW}Warning: gemini CLI not found.${NC}"
    echo "Install Gemini CLI or set up an alias."
    echo ""
    echo "Alternative: Copy the report and paste into Gemini web interface:"
    echo "  cat $REPORT_FILE"
    exit 1
fi

echo -e "${GREEN}Reading report from: $REPORT_FILE${NC}"
echo ""

# Build the prompt
read -r -d '' PROMPT << 'EOF' || true
You are an expert trading analyst. Analyze this trending stocks data and provide a concise morning briefing.

FORMAT YOUR RESPONSE EXACTLY LIKE THIS:

## TOP 3 HIGHEST CONVICTION PLAYS
For each: Ticker, why it's interesting, key risk, suggested approach (watch/nibble/size)

## AVOID / RED FLAGS
Stocks that look like traps, overcrowded, or have concerning signals

## THEME OF THE DAY
What sectors/themes are hot? Any correlations between trending stocks?

## MARKET SENTIMENT
Overall assessment: bullish/bearish/neutral
Key risk factors to watch today

## TODAY'S WATCHLIST (Top 5)
Ticker | Reason | Entry trigger to watch

Be concise and actionable. Skip fluff. This is for a morning trading review.

TRENDING STOCKS DATA:
EOF

# Append the JSON data
FULL_PROMPT="$PROMPT

$(cat "$REPORT_FILE")"

echo -e "${YELLOW}Calling Gemini (gemini-3-pro-preview) for analysis...${NC}"
echo ""

# Call Gemini CLI with latest pro model and capture output
ANALYSIS=$("$GEMINI_CMD" --model gemini-3-pro-preview "$FULL_PROMPT" 2>/dev/null)
EXIT_CODE=$?

if [[ $EXIT_CODE -eq 0 && -n "$ANALYSIS" ]]; then
    # Display to terminal
    echo "$ANALYSIS"

    # Save to file with header
    {
        echo "# Trending Stocks Analysis - $DATE_STR"
        echo ""
        echo "_Generated by Gemini 3 Pro Preview_"
        echo ""
        echo "---"
        echo ""
        echo "$ANALYSIS"
    } > "$OUTPUT_FILE"

    echo ""
    echo -e "${GREEN}=============================================${NC}"
    echo -e "${GREEN}Analysis complete.${NC}"
    echo -e "${GREEN}Saved to: $OUTPUT_FILE${NC}"
    echo -e "${GREEN}=============================================${NC}"
else
    echo ""
    echo -e "${YELLOW}Warning: Gemini analysis failed (exit code: $EXIT_CODE)${NC}"
    echo ""
    echo "Troubleshooting:"
    echo "  1. Check if gemini CLI is properly configured"
    echo "  2. Check your API key / authentication"
    echo "  3. Try running: $GEMINI_CMD --model gemini-3-pro-preview 'test'"
    echo ""
    echo "Manual option: Copy the JSON below and paste into Gemini web:"
    echo "----------------------------------------"
    head -50 "$REPORT_FILE"
    echo "..."
    echo "----------------------------------------"
    exit 1
fi
